### ISSUE TITLE
GPU support?

### ISSUE THREAD

**Issue by amirebrahimi** [QTrkX/qtrkx-gnn-tracking#2]
I can see that the config files support setting `gpu` to a specific gpu id. However, it seems to only set the `CUDA_VISIBLE_DEVICES` environment variable. Cirq by default doesn't seem to use CUDA unless you install qsimcirq, but does TensorFlow make use of CUDA automatically or is vanilla Cirq used underneath?

**Comment by cnktysz** [comment]
I think the gpu option was left from my initial experiments. Cirq and TFQ did not support GPUs at the time I was developing the code, but this is definitely an open development path.
